name: Build, Test & Push Artefact
permissions:
  id-token: write
  contents: write
  actions: read
  checks: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    uses: ./.github/workflows/build_template.yml
    secrets: inherit
    with:
      DOCKER_REPO: ''
      DOCKER_USER: ''
      DOCKER_PASSWORD: ''
      IMAGE_NAME: ''
