name: Build, Test & Push Artefact
permissions:
  id-token: write
  contents: write
  actions: read
  checks: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    uses: ./.github/workflows/build_template.yml
    secrets: inherit
    with:
      docker_images: "['pyimage']" # define array of images to be built. Requires [imagename].Dockerfile files in root directory and names image [imagename]
      DOCKER_REPO: 'ghcr.io/username'
      DOCKER_USER: ''
      DOCKER_PASSWORD: ''
