name: Build, Test & Push Artefact
on:
  push:
    branches:
      - "*"
  # pull_request:
  #   branches:
  #     - master

jobs:
  test-build-push-artefact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v2
      - name: Setup dev packages
        run: |
          sudo apt update
          sudo apt install -y libssl-dev build-essential
      - name: Mount bazel cache  
        uses: actions/cache@v3
        with:
            path: "~/.cache/bazel"
            key: bazel
      - name: Test
        run: bazel test  --test_output=all //...
      - name: Build
        run: bazel build //...